### ISSUE TITLE
cbt passes command as args to the program

### ISSUE THREAD

**Issue by mchav** [cvogt/cbt#132]
If you have `println(args(0))` and you run `cbt run 10`, `run` is printed.

**Comment by benjaminfrank** [comment]
In Stage2.run(...), when assembling the context args, the command is not dropped (only the "meta" commands loop/direct/cross are dropped, but not their subsequent commands).
So maybe it is as easy as dropping the command here, but I don't know if this might break other commands. Dropping only when `run` or `loop run` are given might be an option. @cvogt maybe you remember if dropping the command here is safe? Otherwise I might be able to give it some testing tomorrow (the fix is easy enough)

**Comment by cvogt** [comment]
@benjaminfrank I don't remember. Probably it's fine. And if not we should change cbt to pass the task around as a separate value not inside args.
