### ISSUE TITLE
frege support

### ISSUE THREAD

**Issue by cvogt** [cvogt/cbt#322]
maybe like https://github.com/earldouglas/sbt-frege

**Comment by mchav** [comment]
Working on it. Some issues that came up though. Since the `sourceFiles` function is final in BasicBuild and uses the default sourceFiles filter I can't get it to include `.fr` files. Also a small issue with the resolver, the pom file for frege doesn't have a classfier but the compiler jars do meaning the download crashes.

Would moving the sourceFileFilter to the build class instead of lib be a good idea?

Not sure how to go about addressing the second issue.

**Comment by cvogt** [comment]
@mchav, yes moving sourceFileFilter into the build class and overriding it in the frege plugin to look for .fr files seems like a great solution.

What exactly do you mean exactly by "the compiler jars do" ? What compiler?

**Comment by mchav** [comment]
The jar for the Frege compiler. The jar file is Frege-3.x-jdk-7

**Comment by cvogt** [comment]
I think you can provide a classifier, no? Otherwise we may need to patch the resolver

**Comment by mchav** [comment]
Say I provide a classified. It finds the jar `Frege-3.x-jdk-7.jar` but looks for the pom file `Frege-3.x-jdk-7.pom`. But there isn't such a pom file. Say I don't put a classifier, the problem is reversed, it finds the pom file but not the jar file. The problem is that some packages classify over jars but use a single unclassified pom file. Spark/Hadoop have the same feature so trying to run a Spark project with cbt fails.

**Comment by cvogt** [comment]
mh, I see. This might very well be CBT not adhering to the maven specs. Is the pom file ever supposed to have the classifier?

**Comment by mchav** [comment]
From [here](https://maven.apache.org/pom.html)

"The classifier allows to distinguish artifacts that were built from the same POM but differ in their content. It is some optional and arbitrary string that - if present - is appended to the artifact name just after the version number."

And [this](http://stackoverflow.com/questions/37114624/maven-deploy-two-jars-with-different-classifiers-from-two-separate-pom-xml) suggests it is possible but frowned upon.

**Comment by cvogt** [comment]
makes a lot of sense, how about we give resolve/resolveHash/basePath an argument `useClassifier: Boolean`, set it to true for the jar but to false for the pom file?

**Comment by cvogt** [comment]
looks like this was implemented by https://github.com/cvogt/cbt/pull/330
